website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user

from flask import (
    Flask,
    render_template,
    redirect,
    flash,
    url_for,
    session
)

from datetime import timedelta
from sqlalchemy.exc import (
    IntegrityError,
    DataError,
    DatabaseError,
    InterfaceError,
    InvalidRequestError,
)
from werkzeug.routing import BuildError


from flask_bcrypt import Bcrypt, generate_password_hash, check_password_hash

from flask_login import (
    UserMixin,
    login_user,
    LoginManager,
    current_user,
    logout_user,
    login_required,
)

from . import create_app,db,login_manager,bcrypt
from .models import User
from .forms import login_form, register_form


auth = Blueprint('auth', __name__)


""" @auth.route('/login', methods=['GET', 'POST'], strict_slashes=False)
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user) """

@auth.route('/login/', methods=['GET', 'POST'], strict_slashes=False)
def login():
    form = login_form()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first()
            if user:
                if check_password_hash(user.pwd, form.pwd.data):
                    flash('Logged in successfully!', category='success')
                    login_user(user, remember=True)
                    return redirect(url_for('views.home'))
                else:
                    flash("Invalid Username or password!", "danger")
        except Exception as e:
            flash(e, "danger")

    return render_template("auth.html", user=current_user,
        form=form,
        text="Login",
        title="Login",
        btn_action="Login"
        )


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


""" @auth.route('/sign-up', methods=['GET', 'POST'], strict_slashes=False)
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user) """

# Register route
@auth.route('/register/', methods=['GET', 'POST'], strict_slashes=False)
def register():
    form = register_form()
    if form.validate_on_submit():
        try:
            email = form.email.data
            pwd = form.pwd.data
            username = form.username.data
            
            newuser = User(
                username=username,
                email=email,
                pwd=bcrypt.generate_password_hash(pwd),
            )
    
            db.session.add(newuser)
            db.session.commit()
            login_user(newuser, remember=True)
            flash(f"Account Succesfully created", "success")
            return redirect(url_for("auth.login"))

        except InvalidRequestError:
            db.session.rollback()
            flash(f"Something went wrong!", "danger")
        except IntegrityError:
            db.session.rollback()
            flash(f"User already exists!.", "warning")
        except DataError:
            db.session.rollback()
            flash(f"Invalid Entry", "warning")
        except InterfaceError:
            db.session.rollback()
            flash(f"Error connecting to the database", "danger")
        except DatabaseError:
            db.session.rollback()
            flash(f"Error connecting to the database", "danger")
        except BuildError:
            db.session.rollback()
            flash(f"An error occured !", "danger")
    return render_template("auth.html", user=current_user,
        form=form,
        text="Create account",
        title="Register",
        btn_action="Register account"
        )

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user
from .models import User, Note, Personal, Upload
from . import db
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.urls import url_parse
from .forms import EditProfileForm, PersonalForm, FundingForm
import json
import imghdr
import os
from flask import Flask, render_template, request, redirect, url_for, abort, send_from_directory
from werkzeug.utils import secure_filename
from io import BytesIO
from flask import Flask, render_template, request, send_file
from flask_sqlalchemy import SQLAlchemy
from werkzeug.exceptions import RequestEntityTooLarge
from flask import Flask, abort, make_response, jsonify
from flask import Flask, render_template, session, redirect, url_for
from flask_bootstrap import Bootstrap
from flask_wtf import FlaskForm
import phonenumbers
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError



views = Blueprint('views', __name__)
""" views.config['MAX_CONTENT_LENGTH'] = 10240 * 1024
views.config['UPLOAD_EXTENSIONS'] = ['.jpg', '.png', '.gif', '.pdf', '.doc', '.docx']
views.config['UPLOAD_PATH'] = 'uploads' """



@views.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()

""" @views.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()

    return render_template('user.html', user=current_user) """

@views.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    
    """ posts = [
        {'author': user, 'body': 'Test post #1'},
        {'author': user, 'body': 'Test post #2'}
    ] """
    return render_template('user.html', user=current_user)


@views.route('/edit_profile/', methods=['GET', 'POST'], strict_slashes=False)
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('edit_profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', title='Edit Profile', form=form)



@views.route('/', methods=['GET', 'POST'], strict_slashes=False)
@login_required
def home():
    form = PersonalForm()
    if form.validate_on_submit():
        """ title = [{'titl': 'Ms'}, {'titl': 'Miss'}, {'titl': 'Mrs'}, {'titl': 'Mr'}, {'titl': 'Rev'}, {'titl': 'Dr'}, {'titl': 'Prof'}] """
        title = request.form.get('title')
        flash('title added!', category='success')
        name = request.form.get('name')
        surname = request.form.get('surname')
        idtype = request.form.get('idtype')
        idno = request.form.get('idno')
        passportno = request.form.get('passportno')
        nationality = request.form.get('nationality')
        disability = request.form.get('disability')
        race = request.form.get('race')
        employeeno = request.form.get('employeeno')
        jobtitle = request.form.get('jobtitle')
        phoneno= form.phoneno.data
        department = request.form.get('department')
        municipality = request.form.get('municipality')
        license = request.form.get('license')

        
        newpersonal = Personal(
                        title = title,
                        name = name,
                        surname = surname,
                        idtype = idtype,
                        idno = idno,
                        passportno = passportno,
                        nationality = nationality,
                        disability = disability,
                        race = race,
                        employeeno = employeeno,
                        jobtitle = jobtitle,
                        phoneno = phoneno,
                        department = department,
                        municipality = municipality,
                        license = license,
                    )
                        
        db.session.add(newpersonal) #adding the info to the database 
        db.session.commit()
        flash('Personal info added!', category='success')
       
    return render_template("home.html", user=current_user, form=form)

@views.route('/showphone')
def show_phone():
    return render_template('show_phone.html', phoneno=session['phoneno'])


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in {'doc', 'docx', 'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}

@views.errorhandler(413)
def too_large(e):
    return make_response(jsonify(message="File is too large"), 413)

@views.route('/qualifications/', methods=['GET', 'POST'], strict_slashes=False)
@login_required
def qualifications():
     """ if request.method == 'POST':
        #file = request.files['file']
        file = request.files.get("file")
        print(request.files.get('file'))
        upload = Upload(filename=file.filename, data=file.read())
        db.session.add(upload)
        db.session.commit()
        return f'Uploaded: {file.filename}'
 """
     if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file part', "danger")
            return redirect(request.url)
        file = request.files['file']
        # if user does not select file, browser also
        # submit a empty part without filename
        if file.filename == '':
            flash('No selected file', "danger")
            return redirect(request.url)
        if file and not allowed_file(file.filename):
            return 'File type not allowed', 400
        if file and allowed_file(file.filename):
            #filename = secure_filename(file.filename)
            upload = Upload(filename=secure_filename(file.filename), data=file.read())
            db.session.add(upload)
            db.session.commit()
            flash('File successfully uploaded', "success")
            return f'Uploaded: {file.filename}'
            #return redirect(url_for('uploaded_file', filename=filename))
    
     return render_template("qualifications.html", user=current_user)

@views.route('/qualdetails/', methods=['GET', 'POST'], strict_slashes=False)
@login_required
def qualdetails():
    """ if request.method == 'POST': 
        note = request.form.get('note')#Gets the note from the HTML 

        if len(note) < 1:
            flash('Note is too short!', category='error') 
        else:
            new_note = Note(data=note, user_id=current_user.id)  #providing the schema for the note 
            db.session.add(new_note) #adding the note to the database 
            db.session.commit()
            flash('Note added!', category='success') """

    return render_template("qualdetails.html", user=current_user)


@views.route('/funding/', methods=['GET', 'POST'], strict_slashes=False)
@login_required
def funding():
    """ if request.method == 'POST': 
        note = request.form.get('note')#Gets the note from the HTML 

        if len(note) < 1:
            flash('Note is too short!', category='error') 
        else:
            new_note = Note(data=note, user_id=current_user.id)  #providing the schema for the note 
            db.session.add(new_note) #adding the note to the database 
            db.session.commit()
            flash('Note added!', category='success') """ 

    return render_template("funding.html", user=current_user)


@views.route('/occupation/', methods=['GET', 'POST'], strict_slashes=False)
@login_required
def occupation():
    """ if request.method == 'POST': 
        note = request.form.get('note')#Gets the note from the HTML 

        if len(note) < 1:
            flash('Note is too short!', category='error') 
        else:
            new_note = Note(data=note, user_id=current_user.id)  #providing the schema for the note 
            db.session.add(new_note) #adding the note to the database 
            db.session.commit()
            flash('Note added!', category='success') """

    return render_template("occupation.html", user=current_user)

@views.route('/constraints/', methods=['GET', 'POST'], strict_slashes=False)
@login_required
def constraints():
    """ if request.method == 'POST': 
        note = request.form.get('note')#Gets the note from the HTML 

        if len(note) < 1:
            flash('Note is too short!', category='error') 
        else:
            new_note = Note(data=note, user_id=current_user.id)  #providing the schema for the note 
            db.session.add(new_note) #adding the note to the database 
            db.session.commit()
            flash('Note added!', category='success') """

    return render_template("constraints.html", user=current_user)

@views.route('/membership/', methods=['GET', 'POST'], strict_slashes=False)
@login_required
def membership():
    """ if request.method == 'POST': 
        note = request.form.get('note')#Gets the note from the HTML 

        if len(note) < 1:
            flash('Note is too short!', category='error') 
        else:
            new_note = Note(data=note, user_id=current_user.id)  #providing the schema for the note 
            db.session.add(new_note) #adding the note to the database 
            db.session.commit()
            flash('Note added!', category='success') """

    return render_template("membership.html", user=current_user)

@views.route('/competencies/', methods=['GET', 'POST'], strict_slashes=False)
@login_required
def competencies():

website/templates/auth.html
{% extends "base.html" %}
{% block title %} {{ title }} {% endblock %}

{% block content %}
<div class="container">
    <div class="row mt-4">
        <div class="col-lg-5 col-md-6 m-auto card p-4">
            <form action="{{ request.path }}" method="POST" class="card-body">
                {{ form.csrf_token }}

                

                <div class="text-center">
                    <h2>Skills Audit</h2>
                    <h5 class="text-primary">{{ text }}</h5>
                </div>
                
                {% if request.path == '/register/' %}
                <div class="form-group mb-3">
                    {{ form.username(class_="form-control",placeholder="Username")}}
                </div>
                {% for error in form.username.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ error }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor%}
                {% endif%}
                <div class="form-group mb-3">
                    {{ form.email(class_="form-control",placeholder="Email")}}
                </div>
                {% for error in form.email.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ error }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor%}
                <div class="form-group mb-3">
                    {{ form.pwd(class_="form-control",placeholder="Password")}}
                </div>
                {% for error in form.pwd.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ error }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div> {% endfor%}
                {% if request.path == '/register/' %}
                <div class="form-group mb-3">
                    {{ form.cpwd(class_="form-control",placeholder="Confirm Password")}}
                </div>
                {% for error in form.cpwd.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ error }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div> {% endfor%}
                {% endif %}
                <div class="text-center">

                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-block btn-primary mb-3"> {{ btn_action }} </button>
                    </div>

                    <p>
                        {% if request.path != '/register/' %}
                        New here?
                        <a href="{{url_for('auth.register')}}">Create account</a>
                        {% else %}
                        Already have an account?
                        <a href="{{url_for('auth.login')}}">Login</a>
                        {% endif %}
                    </p>
                    
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

website/templates/base.html
<!doctype html>
 <html lang="en">
 
 <head>
     <!-- Required meta tags -->
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <!-- Bootstrap CSS -->
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.1/min/dropzone.min.css">
     <!-- Sweet alert Js -->
     <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>COGTA NW Skills Audit</title>
    {% endif %}
 </head>
 
 <body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbar"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" id="home" href="{{url_for('views.home')}}">Home</a>
            <a class="nav-item nav-link" id="logout" href="{{url_for('auth.logout')}}">Logout</a>
            <a class="nav-item nav-link" id="profile" href="{{ url_for('views.user', username=current_user.username) }}">Profile</a>
            {% else %}
            <a class="nav-item nav-link" id="login" href="{{url_for('auth.login')}}">Login</a>
            <a class="nav-item nav-link" id="register" style="text-align:right" href="{{url_for('auth.register')}}">Create account</a>
            {% endif %}
          </div>
        </div>
      </nav>
     <div class="container-fluid">
         {% block content %}
         {% endblock %}
     </div>
     <!-- Bootstrap Bundle with Popper -->
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
     <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

{% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
  fetch("/delete-note", {
    method: "POST",
    body: JSON.stringify({ noteId: noteId }),
  }).then((_res) => {
    window.location.href = "/";
  });
  }
</script>
{% endblock %}
</body>
  <div id="footer">
    {% block footer %}
    <p  style="text-align: center">&copy; Copyright <script>document.write(new Date().getFullYear())</script> by <a href="http://peuneo.co.za">Peuneo</a></p>
    {% endblock %}
  </div>
</html>

website/templates/competencies.html
{% extends "base.html" %}
{% block title %}Competencies{% endblock %}

<style>
  a {
    text-decoration: none;
    display: inline-block;
    padding: 8px 16px;
  }
  
  a:hover {
    background-color: #ddd;
    color: black;
  }
  
  .previous {
    background-color: #f1f1f1;
    color: black;
  }
  
  .next {
    background-color: #04AA6D;
    color: white;
  }
  
  .round {
    border-radius: 50%;
  }
</style>

{% block content %}

<div class="container">
  <div class="row mt-4">
    <div class="col-lg-5 col-md-6 m-auto card p-4">
        <form action="{{ url_for('views.competencies') }}" method="POST" class="card-body">  
          <form action="/action_page.php"></form>        
                      <!-- <h4 align="right">Welcome {{ current_user.username }}</h4> -->
            <div class="container py-4">
                <h1 align="center">OCCUPATIONAL COMPETENCES (KPAs)</h1>
                  <br>
                  <h6 align="center">Proficiency Assessment:</h6>
                  <h6 align="center">For this section, the “Source Competency Lookup” document that matches the occupation is needed.</h6>
                  <h6 align="center">NOTE: THE MUNICIPALITY NEEDS TO PROVIDE THE “COMPETENCE SHEET” THAT MATCHES THE OCCUPATION, TO ENABLE THE PARTICIPANT TO COMPLETE THIS SECTION.</h6>
                    </h6>
                  <br>

                    <div>
                      <button type="submit" class="btn btn-primary text-align-left" onclick="window.location.href = '/development'">&laquo; Prev</button>
                      <button type="submit" class="btn btn-primary text-align-left" onclick="window.location.href = '/nationalkpis'">Next &raquo;</button> 
                    </div>
                            
                    <!-- <div>
                      <button type="submit" class="btn btn-primary text-align-left" onclick="window.location.href = '/qualdetails'">&laquo; Prev</button>
                      <button type="submit" class="btn btn-primary text-align-left" onclick="window.location.href = '/occupation'">Next &raquo;</button>
                    </div> -->
          </div>
     
      </form>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
      $("select.selectVal").change(function() {
          let selectedItem = $(this).children("option:selected").val();
          alert("You have selected the name - " + selectedItem);
        });
    });
</script>
<script>
  function changeButtonName(btnId, btnValue) {
      var btn = document.getElementById("i-greitis-dropdown");
  }
</script>
{% endblock %}

website/templates/constraints.html
{% extends "base.html" %}
{% block title %}Funding{% endblock %}
    
<style>
    a {
      text-decoration: none;
      display: inline-block;
      padding: 8px 16px;
    }
    
    a:hover {
      background-color: #ddd;
      color: black;
    }
    
    .previous {
      background-color: #f1f1f1;
      color: black;
    }
    
    .next {
      background-color: #04AA6D;
      color: white;
    }
    
    .round {
      border-radius: 50%;
    }
</style>
{% block content %}
    
<div class="container">
    <div class="row mt-4">
     <div class="col-lg-5 col-md-6 m-auto card p-4">
        <form action="{{ url_for('views.constraints') }}" method="POST" class="card-body">  
            <form action="/action_page.php"></form>        
                          <!-- <h4 align="right">Welcome {{ current_user.username }}</h4> -->
            <div class="container py-4">
                <h1 align="center">Occupational Constraints</h1>
                <br>
                <h6 align="center">If applicable to your occupation, state the constraints that make your job difficult to do</h6>
                <br>

                <form method="POST">
                    <label align="center" for="note1" class="form-label form-select-lg mb-3 text-center">Finance Related Constraints</label>
                    <textarea name="note1" id="note1" class="form-control form-select-lg mb-3" rows="5" cols="10"></textarea>
                    <!-- <br />
                    <div align="center">
                        <button type="submit" class="btn btn-primary">Add Note</button>
                    </div> -->
                </form>

                <form method="POST">
                    <label align="center" for="note2" class="form-label form-select-lg mb-3">Individual Development Related Constraints</label>
                    <textarea name="note2" id="note2" class="form-control  form-select-lg mb-3" rows="5" cols="10"></textarea>
                    <!-- <br />
                    <div align="center">
                        <button type="submit" class="btn btn-primary">Add Note</button>
                    </div> -->
                </form>

                <form method="POST">
                    <label align="center" for="note3" class="form-label form-select-lg mb-3">Work Process Related Constraints</label>
                    <textarea name="note3" id="note3" class="form-control form-select-lg mb-3" rows="5" cols="10"></textarea>
                    <br />
                    <!-- <div align="center">
                        <button type="submit" class="btn btn-primary">Add Note</button>
                    </div> -->
                </form>
                      
                <form method="POST">
                    <label align="center" for="note4" class="form-label form-select-lg mb-3">Stakeholder Relations Constraints</label>
                    <textarea name="note4" id="note4" class="form-control form-select-lg mb-3" rows="5" cols="10"></textarea>
                    <!-- <br />
                    <div align="center">
                        <button type="submit" class="btn btn-primary">Add Note</button>
                    </div> -->
                </form>

                <form method="POST">
                    <label align="center" for="note5" class="form-label form-select-lg mb-3">Other Constraints</label>
                    <textarea name="note5" id="note5" class="form-control form-select-lg mb-3" rows="5" cols="10"></textarea>
                    <!-- <br />
                    <div align="center">
                        <button type="submit" class="btn btn-primary">Add Note</button>
                    </div> -->
                </form>
                <br>
                <div>
                    <button type="submit" class="btn btn-primary text-align-left" onclick="window.location.href = '/occupation'">&laquo; Prev</button>
                    <button type="submit" class="btn btn-primary text-align-left" onclick="window.location.href = '/membership'">Next &raquo;</button> 
                </div>
              </div>        
          </form>
        </div>
    </div>
</div>
    
<script>
    $(document).ready(function() {
        $("select.selectVal").change(function() {
            let selectedItem = $(this).children("option:selected").val();
            alert("You have selected the name - " + selectedItem);
          });
      });
</script>    
<script>
    function changeButtonName(btnId, btnValue) {
        var btn = document.getElementById("i-greitis-dropdown");
    }
</script>
{% endblock %}
    

website/templates/login.html
<!-- {% extends "base.html" %}
{% block content %}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}
 -->

website/templates/sign_up.html
<!-- {% extends "base.html" %}
{% block content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}
 -->